### ISSUE TITLE
07/11 链栈

### ISSUE THREAD

**Issue by xingchen36** [YiQun0422/learning#2]
https://github.com/YiQun0422/learning/blob/7d4e7e5c263b649806900729a2b098714d3289e5/stack.c#L85

修改为：
```cpp
void PushStack(Stack* stack, int value) {
    Stack* p = malloc(sizeof(Stack)); // 生成新结点
    p->data = value;                  // 将新结点数据域置为value
    p->next = NULL;
    p = stack;   
}
```

这个代码和向链表中插入一个元素一摸一样，怎么就不会了呢?  调试一下啊，一步一步走一下，纸上面手写运行一下也可以呀！

**Comment by xingchen36** [comment]
![image](https://github.com/YiQun0422/learning/assets/174160942/3050c2ae-3a9e-4afd-8b9e-de1bd95a0024)
因为参数是 Stack* stack 所以不能修改头节点，所以只能上面这样实现。

书上的方法：一个倒序的链表，这样插入时间复杂度为O(1), 删除复杂度为 O(1), 而我上面的图，插入时间复杂度为O(n), 删除复杂度为 O(n),
![image](https://github.com/YiQun0422/learning/assets/174160942/b6bf4e30-6a3f-4563-af57-0c90b0187c81)

书上的方法参数为  Stack** 所以可以修改栈的头节点，所以可以使用倒序的链表

**Comment by xingchen36** [comment]
现在你有几种选择：
1. 按照书上的方法，把所有的 Stack* 改为 Stack** 但是这样和之前的函数声明不一致了
2. 使用如下的结构体，这个方法和方法一差不多，就是不需要修改函数声明了（保持接口一致）：
```cpp
typedef struct {
    int data;
    struct List* next; // 和单链表一致
} List;
typedef struct {
    struct List* list;
} Stack;
```
3. 继续使用现有方法，只不过时间复杂度比较高（每次必须从头节点遍历到尾巴才能插入或删除）
4. 修改现有方法，降低其时间复杂度：使用双向链表，同时保存头尾指针，这样就不需要每次都遍历到尾巴才能插入或删除

**Comment by YiQun0422** [comment]
hi

**Comment by YiQun0422** [comment]
hello

**Comment by YiQun0422** [comment]
> 现在你有几种选择：
> 
> 1. 按照书上的方法，把所有的 Stack* 改为 Stack** 但是这样和之前的函数声明不一致了
> 2. 使用如下的结构体，这个方法和方法一差不多，就是不需要修改函数声明了（保持接口一致）：
> 
> ```c++
> typedef struct {
>     int data;
>     struct List* next; // 和单链表一致
> } List;
> typedef struct {
>     struct List* list;
> } Stack;
> ```
> 
> 3. 继续使用现有方法，只不过时间复杂度比较高（每次必须从头节点遍历到尾巴才能插入或删除）
> 4. 修改现有方法，降低其时间复杂度：使用双向链表，同时保存头尾指针，这样就不需要每次都遍历到尾巴才能插入或删除

已使用方法二更新代码
