### ISSUE TITLE
快来看看

### ISSUE THREAD

**Issue by YiQun0422** [YiQun0422/learning#3]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/tree.c#L12
太神奇了 把这行BiTNode改成BiNode就一万个错 为什么

**Comment by xingchen812** [comment]
编译器从第一个字往后看，没出现过 BiNode 就不认识。C/C++ 编译器很笨的 不会管你后面的，前面不声明就不认识。

**Comment by xingchen812** [comment]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/tree.c#L54

这样写不好看，最好这样写：
```cpp
	if (!T)
	{
                return;
	}
	printf("%d ", T->data);       // 打印结点数据
	PerOrderTravserse(T->lChild); // 遍历左孩子
	PerOrderTravserse(T->rChild); // 遍历右孩子
```

包括这个，一样的道理，这里不需要else。这样逻辑更清晰，核心宗旨就是减少需要多写缩进的代码行数。
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/tree.c#L73

**Comment by xingchen812** [comment]
现在已经开了三个 "Issue" 了，就是评论的这个，你那边应该有一个 "close" 的功能，可以关闭旧的不需要的，省的搞那么多不知道该看哪个 ...

**Comment by xingchen812** [comment]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/stack.c#L106

这里明显有个错误，else 的时候 返回值 是什么？

**Comment by xingchen812** [comment]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/stack.c#L125
  考试最好别这样写，别写这种连等于，可读性不好，我的建议是这样 。一个人一个习惯，但是也许老师喜欢这种写法？？

**Comment by xingchen812** [comment]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/stack.c#L130

这里这样写没问题。
我说一个题外话，假如 queue->rear 的类型是 unsigned int ，这样写就不对了，应该这样：
```cpp
return (queue->rear + MAXSIZE - queue->front) % MAXSIZE;
```

**Comment by xingchen812** [comment]
https://github.com/YiQun0422/learning/blob/5019c949deea5306a621a4de61c034dd3e2ff215/stack.c#L152

else的时候没有返回值
